import { RiskAssessmentEscores } from "../../pages/RiskAssessmentForm/types/RiskAssessmentFields";

export type RiskAssessment = {
  id: string;
  responsavel: string;
  risco_de_carie_preencher: boolean;
  risco_de_carie_fator?: string;
  risco_de_carie_biofilme?: string;
  risco_de_carie?: number;
  risco_de_carie_anotacoes?: string;
  risco_de_carie_avaliacao?: string;
  risco_periodontal_preencher: boolean;
  risco_periodontal_codigo?: string;
  risco_periodontal_classificacao?: string;
  risco_periodontal_anotacoes?: string;
  risco_periodontal_avaliacao?: string;
  tem_risco_tecidos_moles: boolean;
  risco_tecidos_moles_codigo?: string;
  risco_tecidos_moles_classificacao?: string;
  risco_tecidos_moles_anotacoes?: string;
  risco_tecidos_moles_avaliacao?: string;
  necessidade_de_protese_preencher: boolean;
  uso_de_protese_superior_dimensoes?: string;
  uso_de_protese_superior_codigos?: string;
  uso_de_protese_superior_criterios?: string;
  uso_de_protese_inferior_dimensoes?: string;
  uso_de_protese_inferior_codigos?: string;
  uso_de_protese_inferior_criterios?: string;
  necessidade_de_protese_anotacoes?: string;
  necessidade_de_protese_avaliacao?: string;
  risco_familiar_preencher: boolean;
  risco_familiar_escores?: RiskAssessmentEscores[];
  risco_familiar_anotacoes?: string;
  risco_familiar_avaliacao?: string;
  risco_de_carie_encaminhamento?: string;
  risco_periodontal_criterio: string;
  risco_tecidos_moles_criterio: string;
  local_da_atividade?: string;
  necessidade_de_ART?: boolean;
  ART_realizada?: boolean;
  quantas_ARTs_foram_realizadas?: number;
  created_at: string;
  updated_at: string;
};
